-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 10:57:10 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qapp` DEFAULT CHARACTER SET utf8 ;
USE `qapp` ;

-- -----------------------------------------------------
-- Table `qapp`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`device` (
  `imei` BIGINT NOT NULL,
  `serial` VARCHAR(45) NOT NULL,
  `mac` VARCHAR(45) NOT NULL,
  `device_type_id` VARCHAR(45) NOT NULL,
  `os_id` VARCHAR(45) NOT NULL,
  `major_version` VARCHAR(45) NULL,
  `minor_version` VARCHAR(45) NULL,
  PRIMARY KEY (`imei`),
  UNIQUE INDEX `serial_UNIQUE` (`serial` ASC),
  UNIQUE INDEX `mac_UNIQUE` (`mac` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`user_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `contact` BIGINT(12) NOT NULL,
  `instance_id` VARCHAR(45) NOT NULL,
  `device_imei` BIGINT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `user_status_id` INT NOT NULL DEFAULT 1,
  `creation_time` DATETIME NOT NULL,
  `updation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_contact_UNIQUE` (`contact` ASC),
  INDEX `fk_user_user_status1_idx` (`user_status_id` ASC),
  CONSTRAINT `fk_user_device`
    FOREIGN KEY (`device_imei`)
    REFERENCES `qapp`.`device` (`imei`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_status1`
    FOREIGN KEY (`user_status_id`)
    REFERENCES `qapp`.`user_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`user_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`user_contact` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `contact` BIGINT(12) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_contact_user_idx` (`user_id` ASC),
  UNIQUE INDEX `user_contact_unique` (`user_id` ASC, `contact` ASC),
  CONSTRAINT `fk_user_contact_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `qapp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`friend_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`friend_network` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `friend_user_id` BIGINT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `updation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_friend_network_user1_idx` (`user_id` ASC),
  INDEX `fk_friend_network_user1_idx1` (`friend_user_id` ASC),
  CONSTRAINT `fk_friend_network_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `qapp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_network_user2`
    FOREIGN KEY (`friend_user_id`)
    REFERENCES `qapp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`question` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `owner_id` BIGINT NOT NULL,
  `is_forwardable` TINYINT(1) NOT NULL DEFAULT 1,
  `is_expired` TINYINT(1) NOT NULL DEFAULT 0,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_user1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `qapp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`question_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`question_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`sharing_entity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`sharing_entity_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`question_sharing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`question_sharing` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_id` BIGINT NOT NULL,
  `is_excluded` TINYINT(1) NOT NULL DEFAULT 0,
  `sharing_entity_type_id` INT NOT NULL,
  `sharing_entity_id` BIGINT NOT NULL,
  `is_public_sharing` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_question_sharing_question1_idx` (`question_id` ASC),
  INDEX `fk_question_sharing_sharing_entity_type1_idx` (`sharing_entity_type_id` ASC),
  CONSTRAINT `fk_question_sharing_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `qapp`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_sharing_sharing_entity_type1`
    FOREIGN KEY (`sharing_entity_type_id`)
    REFERENCES `qapp`.`sharing_entity_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`content_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `question_sharing_id` BIGINT NOT NULL,
  `question_sharing_question_id1` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `question_sharing_id`, `question_sharing_question_id1`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC),
  INDEX `fk_content_type_question_sharing1_idx` (`question_sharing_id` ASC, `question_sharing_question_id1` ASC),
  CONSTRAINT `fk_content_type_question_sharing1`
    FOREIGN KEY (`question_sharing_id`)
    REFERENCES `qapp`.`question_sharing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`question_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`question_content` (
  `question_id` BIGINT NOT NULL,
  `question_type_id` INT NOT NULL,
  `content_type_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `updation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`question_id`),
  INDEX `fk_question_content_question_type1_idx` (`question_type_id` ASC),
  INDEX `fk_question_content_content_type1_idx` (`content_type_id` ASC),
  CONSTRAINT `fk_question_content_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `qapp`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_content_question_type1`
    FOREIGN KEY (`question_type_id`)
    REFERENCES `qapp`.`question_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_content_content_type1`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `qapp`.`content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`friend_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`friend_group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  `created_by` BIGINT NOT NULL,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_friend_group_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_friend_group_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `qapp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`friend_group_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`friend_group_member` (
  `group_id` BIGINT NOT NULL,
  `member_user_id` BIGINT NOT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT 0,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`group_id`),
  INDEX `fk_friend_group_member_user1_idx` (`member_user_id` ASC),
  CONSTRAINT `fk_friend_group_member_user1`
    FOREIGN KEY (`member_user_id`)
    REFERENCES `qapp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_group_member_friend_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `qapp`.`friend_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`distribution_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`distribution_list` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `owner_id` BIGINT NOT NULL,
  `friend_user_id` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`answer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_id` BIGINT NOT NULL,
  `owner_id` BIGINT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `updation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_question1_idx` (`question_id` ASC),
  INDEX `fk_answer_user1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `qapp`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `qapp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`answer_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`answer_content` (
  `answer_id` BIGINT NOT NULL,
  `content_type_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`answer_id`),
  CONSTRAINT `fk_answer_content_answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `qapp`.`answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`event_entity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`event_entity_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qapp`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qapp`.`event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_entity_type_id` INT NOT NULL,
  `event_entity_id` BIGINT NOT NULL,
  `sharing_entity_type_id` INT NOT NULL,
  `sharing_entity_id` BIGINT NOT NULL,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_event_event_type1_idx` (`event_entity_type_id` ASC),
  CONSTRAINT `fk_event_event_type1`
    FOREIGN KEY (`event_entity_type_id`)
    REFERENCES `qapp`.`event_entity_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
